// Generated by gencpp from file monstertruck_msgs/GetGazeDirectionRequest.msg
// DO NOT EDIT!


#ifndef MONSTERTRUCK_MSGS_MESSAGE_GETGAZEDIRECTIONREQUEST_H
#define MONSTERTRUCK_MSGS_MESSAGE_GETGAZEDIRECTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace monstertruck_msgs
{
template <class ContainerAllocator>
struct GetGazeDirectionRequest_
{
  typedef GetGazeDirectionRequest_<ContainerAllocator> Type;

  GetGazeDirectionRequest_()
    : stamp()  {
    }
  GetGazeDirectionRequest_(const ContainerAllocator& _alloc)
    : stamp()  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;




  typedef boost::shared_ptr< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetGazeDirectionRequest_

typedef ::monstertruck_msgs::GetGazeDirectionRequest_<std::allocator<void> > GetGazeDirectionRequest;

typedef boost::shared_ptr< ::monstertruck_msgs::GetGazeDirectionRequest > GetGazeDirectionRequestPtr;
typedef boost::shared_ptr< ::monstertruck_msgs::GetGazeDirectionRequest const> GetGazeDirectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace monstertruck_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'monstertruck_msgs': ['/home/evan/share/coverage_path_ws/src/monstertruck_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84d365d08d5fc49dde870daba1c7992c";
  }

  static const char* value(const ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84d365d08d5fc49dULL;
  static const uint64_t static_value2 = 0xde870daba1c7992cULL;
};

template<class ContainerAllocator>
struct DataType< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "monstertruck_msgs/GetGazeDirectionRequest";
  }

  static const char* value(const ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
time stamp\n\
\n\
";
  }

  static const char* value(const ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGazeDirectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MONSTERTRUCK_MSGS_MESSAGE_GETGAZEDIRECTIONREQUEST_H
