// Generated by gencpp from file monstertruck_msgs/LookAt.msg
// DO NOT EDIT!


#ifndef MONSTERTRUCK_MSGS_MESSAGE_LOOKAT_H
#define MONSTERTRUCK_MSGS_MESSAGE_LOOKAT_H

#include <ros/service_traits.h>


#include <monstertruck_msgs/LookAtRequest.h>
#include <monstertruck_msgs/LookAtResponse.h>


namespace monstertruck_msgs
{

struct LookAt
{

typedef LookAtRequest Request;
typedef LookAtResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LookAt
} // namespace monstertruck_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::monstertruck_msgs::LookAt > {
  static const char* value()
  {
    return "574e46e9b1544de88826572f80572960";
  }

  static const char* value(const ::monstertruck_msgs::LookAt&) { return value(); }
};

template<>
struct DataType< ::monstertruck_msgs::LookAt > {
  static const char* value()
  {
    return "monstertruck_msgs/LookAt";
  }

  static const char* value(const ::monstertruck_msgs::LookAt&) { return value(); }
};


// service_traits::MD5Sum< ::monstertruck_msgs::LookAtRequest> should match 
// service_traits::MD5Sum< ::monstertruck_msgs::LookAt > 
template<>
struct MD5Sum< ::monstertruck_msgs::LookAtRequest>
{
  static const char* value()
  {
    return MD5Sum< ::monstertruck_msgs::LookAt >::value();
  }
  static const char* value(const ::monstertruck_msgs::LookAtRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::monstertruck_msgs::LookAtRequest> should match 
// service_traits::DataType< ::monstertruck_msgs::LookAt > 
template<>
struct DataType< ::monstertruck_msgs::LookAtRequest>
{
  static const char* value()
  {
    return DataType< ::monstertruck_msgs::LookAt >::value();
  }
  static const char* value(const ::monstertruck_msgs::LookAtRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::monstertruck_msgs::LookAtResponse> should match 
// service_traits::MD5Sum< ::monstertruck_msgs::LookAt > 
template<>
struct MD5Sum< ::monstertruck_msgs::LookAtResponse>
{
  static const char* value()
  {
    return MD5Sum< ::monstertruck_msgs::LookAt >::value();
  }
  static const char* value(const ::monstertruck_msgs::LookAtResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::monstertruck_msgs::LookAtResponse> should match 
// service_traits::DataType< ::monstertruck_msgs::LookAt > 
template<>
struct DataType< ::monstertruck_msgs::LookAtResponse>
{
  static const char* value()
  {
    return DataType< ::monstertruck_msgs::LookAt >::value();
  }
  static const char* value(const ::monstertruck_msgs::LookAtResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MONSTERTRUCK_MSGS_MESSAGE_LOOKAT_H
