// Generated by gencpp from file monstertruck_msgs/NavigationSolution.msg
// DO NOT EDIT!


#ifndef MONSTERTRUCK_MSGS_MESSAGE_NAVIGATIONSOLUTION_H
#define MONSTERTRUCK_MSGS_MESSAGE_NAVIGATIONSOLUTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace monstertruck_msgs
{
template <class ContainerAllocator>
struct NavigationSolution_
{
  typedef NavigationSolution_<ContainerAllocator> Type;

  NavigationSolution_()
    : header()
    , roll(0.0)
    , nick(0.0)
    , yaw(0.0)
    , droll(0.0)
    , dnick(0.0)
    , dyaw(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , d_x(0.0)
    , d_y(0.0)
    , d_z(0.0)  {
    }
  NavigationSolution_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , roll(0.0)
    , nick(0.0)
    , yaw(0.0)
    , droll(0.0)
    , dnick(0.0)
    , dyaw(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , d_x(0.0)
    , d_y(0.0)
    , d_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _nick_type;
  _nick_type nick;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _droll_type;
  _droll_type droll;

   typedef float _dnick_type;
  _dnick_type dnick;

   typedef float _dyaw_type;
  _dyaw_type dyaw;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _d_x_type;
  _d_x_type d_x;

   typedef float _d_y_type;
  _d_y_type d_y;

   typedef float _d_z_type;
  _d_z_type d_z;




  typedef boost::shared_ptr< ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> const> ConstPtr;

}; // struct NavigationSolution_

typedef ::monstertruck_msgs::NavigationSolution_<std::allocator<void> > NavigationSolution;

typedef boost::shared_ptr< ::monstertruck_msgs::NavigationSolution > NavigationSolutionPtr;
typedef boost::shared_ptr< ::monstertruck_msgs::NavigationSolution const> NavigationSolutionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace monstertruck_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'monstertruck_msgs': ['/home/evan/share/coverage_path_ws/src/monstertruck_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45d93b8c71cb9a03c6be120126e5ff84";
  }

  static const char* value(const ::monstertruck_msgs::NavigationSolution_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45d93b8c71cb9a03ULL;
  static const uint64_t static_value2 = 0xc6be120126e5ff84ULL;
};

template<class ContainerAllocator>
struct DataType< ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> >
{
  static const char* value()
  {
    return "monstertruck_msgs/NavigationSolution";
  }

  static const char* value(const ::monstertruck_msgs::NavigationSolution_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 roll\n\
float32 nick\n\
float32 yaw\n\
float32 droll\n\
float32 dnick\n\
float32 dyaw\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 d_x\n\
float32 d_y\n\
float32 d_z\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::monstertruck_msgs::NavigationSolution_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.roll);
      stream.next(m.nick);
      stream.next(m.yaw);
      stream.next(m.droll);
      stream.next(m.dnick);
      stream.next(m.dyaw);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.d_x);
      stream.next(m.d_y);
      stream.next(m.d_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigationSolution_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::monstertruck_msgs::NavigationSolution_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::monstertruck_msgs::NavigationSolution_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "nick: ";
    Printer<float>::stream(s, indent + "  ", v.nick);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "droll: ";
    Printer<float>::stream(s, indent + "  ", v.droll);
    s << indent << "dnick: ";
    Printer<float>::stream(s, indent + "  ", v.dnick);
    s << indent << "dyaw: ";
    Printer<float>::stream(s, indent + "  ", v.dyaw);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "d_x: ";
    Printer<float>::stream(s, indent + "  ", v.d_x);
    s << indent << "d_y: ";
    Printer<float>::stream(s, indent + "  ", v.d_y);
    s << indent << "d_z: ";
    Printer<float>::stream(s, indent + "  ", v.d_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MONSTERTRUCK_MSGS_MESSAGE_NAVIGATIONSOLUTION_H
