// Generated by gencpp from file monstertruck_msgs/ServoCommand.msg
// DO NOT EDIT!


#ifndef MONSTERTRUCK_MSGS_MESSAGE_SERVOCOMMAND_H
#define MONSTERTRUCK_MSGS_MESSAGE_SERVOCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace monstertruck_msgs
{
template <class ContainerAllocator>
struct ServoCommand_
{
  typedef ServoCommand_<ContainerAllocator> Type;

  ServoCommand_()
    : id(0)
    , position(0.0)  {
    }
  ServoCommand_(const ContainerAllocator& _alloc)
    : id(0)
    , position(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef float _position_type;
  _position_type position;


    static const float DISABLE;
 

  typedef boost::shared_ptr< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ServoCommand_

typedef ::monstertruck_msgs::ServoCommand_<std::allocator<void> > ServoCommand;

typedef boost::shared_ptr< ::monstertruck_msgs::ServoCommand > ServoCommandPtr;
typedef boost::shared_ptr< ::monstertruck_msgs::ServoCommand const> ServoCommandConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const float
      ServoCommand_<ContainerAllocator>::DISABLE =
        
          999.0
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::monstertruck_msgs::ServoCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace monstertruck_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'monstertruck_msgs': ['/home/evan/share/coverage_path_ws/src/monstertruck_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b8ae92b8ba5e2ca96969db3b6b4d5fc";
  }

  static const char* value(const ::monstertruck_msgs::ServoCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b8ae92b8ba5e2caULL;
  static const uint64_t static_value2 = 0x96969db3b6b4d5fcULL;
};

template<class ContainerAllocator>
struct DataType< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "monstertruck_msgs/ServoCommand";
  }

  static const char* value(const ::monstertruck_msgs::ServoCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n\
float32 position\n\
float32 DISABLE = 999.0\n\
";
  }

  static const char* value(const ::monstertruck_msgs::ServoCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::monstertruck_msgs::ServoCommand_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MONSTERTRUCK_MSGS_MESSAGE_SERVOCOMMAND_H
