// Generated by gencpp from file monstertruck_msgs/ServoCommands.msg
// DO NOT EDIT!


#ifndef MONSTERTRUCK_MSGS_MESSAGE_SERVOCOMMANDS_H
#define MONSTERTRUCK_MSGS_MESSAGE_SERVOCOMMANDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <monstertruck_msgs/ServoCommand.h>

namespace monstertruck_msgs
{
template <class ContainerAllocator>
struct ServoCommands_
{
  typedef ServoCommands_<ContainerAllocator> Type;

  ServoCommands_()
    : servo()  {
    }
  ServoCommands_(const ContainerAllocator& _alloc)
    : servo(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> >::other >  _servo_type;
  _servo_type servo;




  typedef boost::shared_ptr< ::monstertruck_msgs::ServoCommands_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::monstertruck_msgs::ServoCommands_<ContainerAllocator> const> ConstPtr;

}; // struct ServoCommands_

typedef ::monstertruck_msgs::ServoCommands_<std::allocator<void> > ServoCommands;

typedef boost::shared_ptr< ::monstertruck_msgs::ServoCommands > ServoCommandsPtr;
typedef boost::shared_ptr< ::monstertruck_msgs::ServoCommands const> ServoCommandsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::monstertruck_msgs::ServoCommands_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::monstertruck_msgs::ServoCommands_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace monstertruck_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'monstertruck_msgs': ['/home/evan/share/coverage_path_ws/src/monstertruck_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::monstertruck_msgs::ServoCommands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::monstertruck_msgs::ServoCommands_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::monstertruck_msgs::ServoCommands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::monstertruck_msgs::ServoCommands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monstertruck_msgs::ServoCommands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monstertruck_msgs::ServoCommands_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::monstertruck_msgs::ServoCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "370e1168616fe3787707a7aa29404a95";
  }

  static const char* value(const ::monstertruck_msgs::ServoCommands_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x370e1168616fe378ULL;
  static const uint64_t static_value2 = 0x7707a7aa29404a95ULL;
};

template<class ContainerAllocator>
struct DataType< ::monstertruck_msgs::ServoCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "monstertruck_msgs/ServoCommands";
  }

  static const char* value(const ::monstertruck_msgs::ServoCommands_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::monstertruck_msgs::ServoCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ServoCommand[] servo\n\
\n\
================================================================================\n\
MSG: monstertruck_msgs/ServoCommand\n\
uint8 id\n\
float32 position\n\
float32 DISABLE = 999.0\n\
";
  }

  static const char* value(const ::monstertruck_msgs::ServoCommands_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::monstertruck_msgs::ServoCommands_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoCommands_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::monstertruck_msgs::ServoCommands_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::monstertruck_msgs::ServoCommands_<ContainerAllocator>& v)
  {
    s << indent << "servo[]" << std::endl;
    for (size_t i = 0; i < v.servo.size(); ++i)
    {
      s << indent << "  servo[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> >::stream(s, indent + "    ", v.servo[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MONSTERTRUCK_MSGS_MESSAGE_SERVOCOMMANDS_H
