(cl:defpackage monstertruck_msgs-srv
  (:use )
  (:export
   "SETALTERNATIVETOLERANCE"
   "<SETALTERNATIVETOLERANCE-REQUEST>"
   "SETALTERNATIVETOLERANCE-REQUEST"
   "<SETALTERNATIVETOLERANCE-RESPONSE>"
   "SETALTERNATIVETOLERANCE-RESPONSE"
   "GETGAZEDIRECTION"
   "<GETGAZEDIRECTION-REQUEST>"
   "GETGAZEDIRECTION-REQUEST"
   "<GETGAZEDIRECTION-RESPONSE>"
   "GETGAZEDIRECTION-RESPONSE"
   "LOOKAT"
   "<LOOKAT-REQUEST>"
   "LOOKAT-REQUEST"
   "<LOOKAT-RESPONSE>"
   "LOOKAT-RESPONSE"
  ))

