// Generated by gencpp from file hector_move_base_msgs/MoveBaseActionExplore.msg
// DO NOT EDIT!


#ifndef HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEACTIONEXPLORE_H
#define HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEACTIONEXPLORE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <hector_move_base_msgs/MoveBaseExplore.h>

namespace hector_move_base_msgs
{
template <class ContainerAllocator>
struct MoveBaseActionExplore_
{
  typedef MoveBaseActionExplore_<ContainerAllocator> Type;

  MoveBaseActionExplore_()
    : header()
    , goal_id()
    , goal()  {
    }
  MoveBaseActionExplore_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::hector_move_base_msgs::MoveBaseExplore_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> const> ConstPtr;

}; // struct MoveBaseActionExplore_

typedef ::hector_move_base_msgs::MoveBaseActionExplore_<std::allocator<void> > MoveBaseActionExplore;

typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseActionExplore > MoveBaseActionExplorePtr;
typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseActionExplore const> MoveBaseActionExploreConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hector_move_base_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'hector_move_base_msgs': ['/home/evan/share/coverage_path_ws/src/hector_move_base_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f099efa6d81450c557f59f9dfac4454";
  }

  static const char* value(const ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f099efa6d81450cULL;
  static const uint64_t static_value2 = 0x557f59f9dfac4454ULL;
};

template<class ContainerAllocator>
struct DataType< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hector_move_base_msgs/MoveBaseActionExplore";
  }

  static const char* value(const ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
actionlib_msgs/GoalID goal_id\n\
MoveBaseExplore goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: hector_move_base_msgs/MoveBaseExplore\n\
float32 speed\n\
";
  }

  static const char* value(const ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveBaseActionExplore_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::hector_move_base_msgs::MoveBaseExplore_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEACTIONEXPLORE_H
